### ISSUE TITLE
Updated href on website

### ISSUE THREAD

**Issue by EliottTKN** [tokencard/tokencard.github.io#11]
In top nav menu change

- [x] Community: token.trydiscourse.com with community.tokencard.io
- [x] Blog: https://medium.com/@MonolithStudio with https://medium.com/@TokenCard

In the the footer change

- [x] Community: token.trydiscourse.com with community.tokencard.io
- [x] Blog: https://medium.com/@MonolithStudio with https://medium.com/@TokenCard

**Comment by miketoken** [comment]
This has been updated, just waiting to be reviewed

**Comment by miketoken** [comment]
That has been sorted and tested
